language: python
python:
  - "3.4"
sudo: required

before_install:
  # - PYTHONPATH="${PYTHONPATH}:$HOME/travis/build/ishovkun"
  # - export PYTHONPATH
  - export PYTHONPATH=$HOME/travis/build/ishovkun

install:
  # - sudo apt install python3-pyside
  - pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/
  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
  - pip3 install configobj
  - pip3 install regex
  - pip3 install pyqtgraph
  # - pip install -r numpy scipy pyside pyqtgraph configobj regex
  - python3 -c "import PySide; print(PySide)"
  - pwd
script:
  - python3 test/sonic_test.py
  # - py.test --cov-report term-missing --cov app -v
