language: python
python:
  - "3.4"
sudo: required

before_install:
 - sudo apt-get install -qq python3-numpy python3-scipy python3-pyside

install:
  - sudo apt install python3-pyside
  - pip3 install configobj
  - pip3 install regex
  - pip3 install pyqtgraph
  # - pip install -r numpy scipy pyside pyqtgraph configobj regex
  - python3 -c "import PySide; print(PySide)"
script:
  - python3 test/sonic_test.py
  # - py.test --cov-report term-missing --cov app -v
