language: python
python:
  - "3.4"
cache: pip
install:
  # - pip3 install numpy scipy
  - pip3 install configobj
  - pip3 install regex
  - travis_wait pip3 install PySide
  - pip3 install pyqtgraph
  # - pip install -r numpy scipy pyside pyqtgraph configobj regex
script:
  - python test/sonic_test.py
  # - py.test --cov-report term-missing --cov app -v
