language: python
python:
  - "3.5"
cache: pip
install:
  - pip install numpy scipy pyside pyqtgraph configobj regex
  # - pip install -r numpy scipy pyside pyqtgraph configobj regex
script:
  - test/sonic_test.py
  # - py.test --cov-report term-missing --cov app -v
