language: python
python:
  - "3.4"
sudo: required

install:
  # - sudo apt install python3-pyside
  - sudo apt install libqt4-gui
  - pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/
  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
  - pip3 install configobj
  - pip3 install regex
  - pip3 install pyqtgraph
  - pip install PyOpenGL
  - pip install scipy
  # - pip install -r numpy scipy pyside pyqtgraph configobj regex
  - python3 -c "import PySide; print(PySide)"
  - pwd

before_script:
  # - export PYTHONPATH=$PYTHONPATH:/home/travis/build/ishovkun
  - export PYTHONPATH=$PYTHONPATH:$HOME/build/ishovkun
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - python test/sonic_test.py
  - python sonic_test_moduli.py
  - python Sonic1.py
  - python Mohr_test.py
  - python geo_test1.py
  - python combo_test.py
